In [1]:
!pip install -U bitsandbytes trl

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting trl
  Downloading trl-1.6.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.4.6)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.2)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.13.0)
Requirement already satisfied: datasets>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from trl) (4.8.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.0.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.10.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Collecting cuda-bindings==12.9.4 (from torch<3,>=2.3->bitsandbytes)
  Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3,>=2.3->bitsandbytes) (1.5.4)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.24.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.4.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.24.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.1.2)
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 27.6 MB/s eta 0:00:00:00:0100:01
Downloading trl-1.6.0-py3-none-any.whl (825 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 825.1/825.1 kB 38.3 MB/s eta 0:00:00
Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 97.3 MB/s eta 0:00:00:00:010:01
Installing collected packages: cuda-bindings, bitsandbytes, trl
  Attempting uninstall: cuda-bindings
    Found existing installation: cuda-bindings 13.2.0
    Uninstalling cuda-bindings-13.2.0:
      Successfully uninstalled cuda-bindings-13.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.
Successfully installed bitsandbytes-0.49.2 cuda-bindings-12.9.4 trl-1.6.0

In [2]:
!pip install -q evaluate rouge_score bert_score

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 3.9 MB/s eta 0:00:00

In [3]:
from transformers import AutoModelForCausalLM, BitsAndBytesConfig, AutoTokenizer,  DataCollatorForSeq2Seq
from peft import LoraConfig, get_peft_model, TaskType, prepare_model_for_kbit_training
from datasets import load_dataset
import torch
import numpy as np
import json

In [4]:
# Definizione delle costanti
N_EPOCHS = 3
LR = 1e-4


MAX_CONTEXT_LENGTH = 2048
MAX_CLAIM_LENGTH = 512
MAX_POST_LENGTH = MAX_CONTEXT_LENGTH - MAX_CLAIM_LENGTH

In [5]:
# Carichiamo il dataset da Hugging Face
dataset = load_dataset("DanRus21/gym_3claim")["train"]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

dataset_claims.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/409 [00:00<?, ? examples/s]

In [6]:
# Splittiamo il dataset in train, validation e test
train_test = dataset.train_test_split(test_size=0.2, seed=1) # 80% train set, 20% test set

# A partire dal training set ricaviamo il validation set
train_val = train_test['train'].train_test_split(test_size=0.2, seed=1) # 80% nuovo train set, 20% validation set

train_test['train'] = train_val['train']
train_test['validation'] = train_val['test']

dataset = train_test

print(dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'claims'],
        num_rows: 261
    })
    test: Dataset({
        features: ['text', 'claims'],
        num_rows: 82
    })
    validation: Dataset({
        features: ['text', 'claims'],
        num_rows: 66
    })
})

In [7]:
print(dataset["train"][0])

{'text': "--- POST EVENTS ---\n\nTitolo: Open Day Federazione Italiana Bodybuilding - Roma, Gennaio 2027\n\nLa FBBI (Federazione Bodybuilding e Fitness Italia) organizza il suo Open Day annuale il 10 gennaio 2027 presso il Centro Fitness Roma Eur, aperto a tutti gli atleti interessati a iniziare il percorso agonistico nel bodybuilding natural.\n\nCOSA TROVERAI\n    1. Consulenza con i Giudici: Sessioni di feedback gratuito con i giudici federali su posing, condizionamento fisico e categorie di appartenenza in base al tuo fisico attuale.\n    2. Presentazione del Calendario Gare 2027: Illustrazione del circuito nazionale e regionale di tutte le categorie, dalle prime gare amatoriali al circuito Pro.\n    3. Workshop sul Posing: 2 ore di lezione pratica di posing maschile e femminile, diviso per categorie (Bikini, Classic Physique, Men's Physique, Figure).\n\nINFORMAZIONI\n    1. Ingresso gratuito previa registrazione sul portale FBBI entro il 5 gennaio 2027.\n    2. Luogo: Centro Fitness Roma Eur, Viale dell'Architettura 20, Roma.\n\nFonti:\n- Titolo: Open Day FBBI 2027 - Comunicato Ufficiale, Fonte: [https://www.fbbi.it/open-day-2027](https://www.fbbi.it/open-day-2027)\n- Titolo: Calendario eventi bodybuilding Italia 2027 - Natural BB Magazine, Fonte: [https://www.naturalbodybuilding-mag.it/open-day-fbbi-gennaio-2027](https://www.naturalbodybuilding-mag.it/open-day-fbbi-gennaio-2027)", 'claims': ["L'Open Day FBBI si terrà il 10 gennaio 2027 presso il Centro Fitness Roma Eur di Viale dell'Architettura 20.", "L'ingresso è gratuito previa registrazione sul portale FBBI entro il 5 gennaio 2027.", "L'evento include un workshop pratico di 2 ore sul posing, suddiviso per categorie (Bikini, Classic Physique, Men's Physique, Figure)."]}

In [7]:
# Carichiamo il modello
model_checkpoint = "Qwen/Qwen2.5-1.5B-Instruct"

quant_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16, bnb_4bit_quant_type="nf4")

base_model = AutoModelForCausalLM.from_pretrained(model_checkpoint, dtype=torch.float16, quantization_config=quant_config, device_map="auto")

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [9]:
base_model

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 1536)
    (layers): ModuleList(
      (0-27): 28 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear4bit(in_features=1536, out_features=1536, bias=True)
          (k_proj): Linear4bit(in_features=1536, out_features=256, bias=True)
          (v_proj): Linear4bit(in_features=1536, out_features=256, bias=True)
          (o_proj): Linear4bit(in_features=1536, out_features=1536, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear4bit(in_features=1536, out_features=8960, bias=False)
          (up_proj): Linear4bit(in_features=1536, out_features=8960, bias=False)
          (down_proj): Linear4bit(in_features=8960, out_features=1536, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((1536,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=1536, out_features=151936, bias=False)
)

Per il Data Collator:
* model=base_model: aiuta il collator a capire i dettagli sui token speciali
* padding=True: padding dinamico alla lunghezza massima del batch corrente
* return_tensors="pt": restituisce i tensori PyTorch

In [8]:
# Carichiamo il tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint, padding_side="right")

# Impostiamo il token EOS come token di padding se quest'ultimo è None
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Carichiamo il Data Collator
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=base_model, padding=True, return_tensors="pt")

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [11]:
# Configurazione dei parametri di LoRA
lora_config = LoraConfig(
    r=8, 
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

In [12]:
# Preparazione del modello quantizzato al training a k-bit
base_model = prepare_model_for_kbit_training(base_model)

model_lora = get_peft_model(base_model, lora_config)

print(model_lora)

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen2ForCausalLM(
      (model): Qwen2Model(
        (embed_tokens): Embedding(151936, 1536)
        (layers): ModuleList(
          (0-27): 28 x Qwen2DecoderLayer(
            (self_attn): Qwen2Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1536, out_features=1536, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=1536, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1536, out_features=256, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=256, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1536, out_features=256, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=256, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=1536, out_features=1536, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=1536, out_features=8, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=8, out_features=1536, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
            )
            (mlp): Qwen2MLP(
              (gate_proj): Linear4bit(in_features=1536, out_features=8960, bias=False)
              (up_proj): Linear4bit(in_features=1536, out_features=8960, bias=False)
              (down_proj): Linear4bit(in_features=8960, out_features=1536, bias=False)
              (act_fn): SiLUActivation()
            )
            (input_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
            (post_attention_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
          )
        )
        (norm): Qwen2RMSNorm((1536,), eps=1e-06)
        (rotary_emb): Qwen2RotaryEmbedding()
      )
      (lm_head): Linear(in_features=1536, out_features=151936, bias=False)
    )
  )
)

In [13]:
model_lora.print_trainable_parameters()

trainable params: 2,179,072 || all params: 1,545,893,376 || trainable%: 0.1410

In [9]:
# Formattiamo il dataset nel tipo che si aspetta SFTTrainer
def preprocess_dataset(example):
    return {
        "messages": [
            {
                "role": "system", 
                 "content": "Sei un sistema di estrazione dati in lingua italiana. Rispondi SEMPRE E SOLO in formato JSON: {'claims': ['claim1', 'claim2', 'claim3']}. Non inventare informazioni."
            },
            {
                "role": "user", 
                "content": f"Estrai le 3 affermazioni più importanti e verificabili dal post:\n\n{example['text']}"
            },
            {
                "role": "assistant", 
                "content": json.dumps({"claims": example["claims"]}, ensure_ascii=False)
            }
        ]
    }

In [10]:
# Applichiamo il processamento a tutto il dataset
dataset = dataset.map(preprocess_dataset, remove_columns=dataset["train"].column_names)

Map:   0%|          | 0/261 [00:00<?, ? examples/s]

Map:   0%|          | 0/82 [00:00<?, ? examples/s]

Map:   0%|          | 0/66 [00:00<?, ? examples/s]

In [16]:
print(dataset["train"]["messages"][0])

[{'role': 'system', 'content': "Sei un sistema di estrazione dati in lingua italiana. Rispondi SEMPRE E SOLO in formato JSON: {'claims': ['claim1', 'claim2', 'claim3']}. Non inventare informazioni."}, {'role': 'user', 'content': "Estrai le 3 affermazioni più importanti e verificabili dal post:\n\n--- POST EVENTS ---\n\nTitolo: Open Day Federazione Italiana Bodybuilding - Roma, Gennaio 2027\n\nLa FBBI (Federazione Bodybuilding e Fitness Italia) organizza il suo Open Day annuale il 10 gennaio 2027 presso il Centro Fitness Roma Eur, aperto a tutti gli atleti interessati a iniziare il percorso agonistico nel bodybuilding natural.\n\nCOSA TROVERAI\n    1. Consulenza con i Giudici: Sessioni di feedback gratuito con i giudici federali su posing, condizionamento fisico e categorie di appartenenza in base al tuo fisico attuale.\n    2. Presentazione del Calendario Gare 2027: Illustrazione del circuito nazionale e regionale di tutte le categorie, dalle prime gare amatoriali al circuito Pro.\n    3. Workshop sul Posing: 2 ore di lezione pratica di posing maschile e femminile, diviso per categorie (Bikini, Classic Physique, Men's Physique, Figure).\n\nINFORMAZIONI\n    1. Ingresso gratuito previa registrazione sul portale FBBI entro il 5 gennaio 2027.\n    2. Luogo: Centro Fitness Roma Eur, Viale dell'Architettura 20, Roma.\n\nFonti:\n- Titolo: Open Day FBBI 2027 - Comunicato Ufficiale, Fonte: [https://www.fbbi.it/open-day-2027](https://www.fbbi.it/open-day-2027)\n- Titolo: Calendario eventi bodybuilding Italia 2027 - Natural BB Magazine, Fonte: [https://www.naturalbodybuilding-mag.it/open-day-fbbi-gennaio-2027](https://www.naturalbodybuilding-mag.it/open-day-fbbi-gennaio-2027)"}, {'role': 'assistant', 'content': '{"claims": ["L\'Open Day FBBI si terrà il 10 gennaio 2027 presso il Centro Fitness Roma Eur di Viale dell\'Architettura 20.", "L\'ingresso è gratuito previa registrazione sul portale FBBI entro il 5 gennaio 2027.", "L\'evento include un workshop pratico di 2 ore sul posing, suddiviso per categorie (Bikini, Classic Physique, Men\'s Physique, Figure)."]}'}]

In [11]:
import json
import re

def extract_claims(text):
    try:
        text = text.replace("```json", "").replace("```", "").strip()
        
        # Isoliamo solo la parte tra {}
        match = re.search(r'\{.*\}', text, re.DOTALL)
        
        if match:
            json_str = match.group(0)
            
            # Correggiamo il bug ]]
            json_str = json_str.replace("]]}", "]}") 
            
            obj = json.loads(json_str)
            claims = obj.get("claims", [])
            
            claims_list = []
            if isinstance(claims, str):
                claims_list = [c.strip() for c in claims.split("|") if c.strip()]
            elif isinstance(claims, list):
                claims_list = [str(c).strip() for c in claims if str(c).strip()]

            if claims_list:
                return " ".join(claims_list[:3])
            
        return "."
    except Exception as e:
        return "."

* output_dir = cartella nella quale vengono salvati i risultati del training
* per_device_train_batch_size = numero di dati elaborati contemporaneamente durante il training
* gradient_accumulation_steps = numero di step dopo il quale si aggiornano i pesi
* report_to="none" = disabilitiamo invio dei log a piattaforme esterne
* eval_strategy="epoch" = la validation loss viene calcolata alla fine di ogni epoca
* save_strategy="epoch" = il chechpoint viene salvato alla fine di ogni epoca
* max_length = lunghezza max input
* assistant_only_loss=True = i pesi vengono aggiornati solo sulle risposte dell'assistente non sul prompt dell'utente
* optim, gradient_checkpointing, gradient_checkpointing_kwargs = tecniche di ottimizzazione della memoria
* fp16 e b16 = False = modello usa la precisione standard a 32-bit

In [14]:
from trl import SFTTrainer, SFTConfig

training_args = SFTConfig(
    output_dir="./finetuning_output",
    learning_rate=LR,
    num_train_epochs=N_EPOCHS,
    
    per_device_train_batch_size=2, 
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,

    report_to="none",
    max_length=MAX_CONTEXT_LENGTH,
    assistant_only_loss=True,
    eval_strategy="epoch",
    save_strategy="epoch",
    
    optim="adamw_8bit",
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    fp16=False,
    bf16=False,
)

trainer_lora = SFTTrainer(
    model=model_lora,                    
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
)

/tmp/ipykernel_58/2302637616.py:3: FutureWarning: The default `loss_type` will change from `'nll'` to `'chunked_nll'` in TRL 1.7. For standard models this is transparent (same math, lower memory) and no action is needed — you'll get the new default automatically on upgrade. If you use a custom model, check ahead of time that `loss_type='chunked_nll'` runs and yields the same loss as `'nll'`; if it doesn't, pin `loss_type='nll'` to keep the current behavior and please open an issue at https://github.com/huggingface/trl/issues so we can address the edge case.
  training_args = SFTConfig(

NameError: name 'model_lora' is not defined

In [20]:
trainer_lora.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=99, training_loss=0.7102785206804372, metrics={'train_runtime': 1020.6563, 'train_samples_per_second': 0.767, 'train_steps_per_second': 0.097, 'total_flos': 5178291768622080.0, 'train_loss': 0.7102785206804372, 'epoch': 3.0})

In [12]:
import evaluate

rouge = evaluate.load("rouge")
bertscore = evaluate.load("bertscore")

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

In [13]:
import torch
import numpy as np
from tqdm.auto import tqdm

def evaluate_metrics(model, dataset):
    model.eval()
    training_padding_side = tokenizer.padding_side
    tokenizer.padding_side = "left"
    
    all_preds = []
    all_labels = []
    i = 1
    
    with torch.no_grad():
        for example in tqdm(dataset, desc="Generazione claims"):
            messages = example["messages"]
            user_message = messages[1]["content"]
            label_text = messages[2]["content"]

            # Formattiamo il prompt
            prompt_str = tokenizer.apply_chat_template([
                {"role": "system", "content": "Sei un sistema di estrazione dati che lavora ESCLUSIVAMENTE sul testo fornito dall'utente. Il tuo compito è analizzare il testo e estrarre le informazioni presenti. Rispondi ESCLUSIVAMENTE in lingua italiana. Se un'informazione non è nel testo, non includerla. Rispondi SOLO in formato JSON: {'claims': ['claim1', 'claim2', 'claim3']} senza aggiungere altre informazioni."},
                {"role": "user", "content": f"Estrai le 3 affermazioni più importanti e verificabili dal post:\n\n{user_message}"}
            ], tokenize=False, add_generation_prompt=True)

            # Trasformiamo il prompt_str in token
            inputs = tokenizer(prompt_str, return_tensors="pt").to(model.device)

            # Usiamo il modello in inferenza
            outputs = model.generate(
                **inputs,
                max_new_tokens=MAX_CLAIM_LENGTH,        
                do_sample=False, # output deterministico
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id
            )

            # Numero di token 
            input_length = inputs.input_ids.shape[1]

            # Prendiamo solo i token generati
            generated_tokens = outputs[0][input_length:]

            # Convertiamo i token in una stringa
            pred_text = tokenizer.decode(generated_tokens, skip_special_tokens=True)

            if i == 2:
                print("-" * 50)
                print(f"POST ORIGINALE:\n{user_message}...") 
                print(f"TARGET CLAIM:\n{label_text}")
                print(f"CLAIM ESTRATTI (Modello):\n{pred_text}")
            
            all_preds.append(extract_claims(pred_text))
            all_labels.append(extract_claims(label_text))

            i += 1
    
    # Ripristina il padding originale
    tokenizer.padding_side = training_padding_side
    
    print("Calcolo ROUGE e BERTScore in corso...")
    rouge_result = rouge.compute(predictions=all_preds, references=all_labels)
    bert_result = bertscore.compute(predictions=all_preds, references=all_labels, lang="it")
    bert_f1 = np.mean(bert_result["f1"])
    
    print("\n**** METRICHE ****")
    print(f"ROUGE-1: {rouge_result['rouge1']:.4f}")
    print(f"ROUGE-2: {rouge_result['rouge2']:.4f}")
    print(f"ROUGE-L: {rouge_result['rougeL']:.4f}")
    print(f"BERTScore F1: {bert_f1:.4f}\n")

In [23]:
evaluate_metrics(model=model_lora, dataset=dataset["validation"])

Generazione claims:   0%|          | 0/66 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

--------------------------------------------------
POST ORIGINALE:
Estrai le 3 affermazioni più importanti e verificabili dal post:

--- POST HOW_TO ---

Titolo: Impostare una Scheda di Forza con Periodizzazione Lineare Semplice per Principianti

La periodizzazione lineare semplice (SLP) è il metodo di programmazione più efficace e validato per principianti e intermedi. Consiste nell'aumentare il carico di allenamento in modo progressivo e sistematico, sessione dopo sessione.

1. PRINCIPIO DI BASE
    1. Sovraccarico progressivo: Ogni sessione di allenamento deve essere leggermente più sfidante della precedente. Per i principianti, aumenti di 2,5 kg a sessione sugli esercizi di spinta (panca, overhead press) e di 5 kg sugli esercizi di tiro e gambe (squat, stacco) sono sostenibili per mesi.
    2. Frequenza: 3 sessioni per settimana (es. lunedì/mercoledì/venerdì), alternando due schemi giornalieri (Giorno A e Giorno B).

2. STRUTTURA DEI GIORNI
    1. Giorno A: Squat 3x5 / Panca Piana 3x5 / Stacco da Terra 1x5
    2. Giorno B: Squat 3x5 / Overhead Press 3x5 / Rematore con Bilanciere 3x5
    3. Gli esercizi principali vengono alternati: La panca si alterna con l'overhead press, entrambe eseguite 1,5 volte a settimana in media.

3. REGOLE PER GLI AUMENTI DI CARICO
    1. Se completi tutte le ripetizioni con la tecnica corretta: aumenta il carico alla sessione successiva secondo i salti programmati.
    2. Se fallisci le ripetizioni per 3 sessioni consecutive sullo stesso esercizio: è il segnale per eseguire un 'reset' del 10-15% del carico e riprendere la progressione.

4. QUANDO PASSARE A UNA PERIODIZZAZIONE PIÙ AVANZATA
    1. Quando la progressione lineare si stalla definitivamente (dopo i reset ripetuti): è il momento di passare a una periodizzazione ondulante o a blocchi.

Fonti:
- Titolo: Starting Strength: Basic Barbell Training (3rd Edition) - Mark Rippetoe, Fonte: [https://www.startingstrength.com/resources/basic-barbell-training](https://www.startingstrength.com/resources/basic-barbell-training)
- Titolo: La periodizzazione lineare per principianti: guida applicata - ForteOggiPiùDiIeri, Fonte: [https://www.forteoggipuidiieri.it/periodizzazione-lineare-principianti](https://www.forteoggipuidiieri.it/periodizzazione-lineare-principianti)...
TARGET CLAIM:
{"claims": ["Per i principianti, aumenti di 2,5 kg a sessione sugli esercizi di spinta e di 5 kg sugli esercizi di tiro e gambe sono sostenibili per mesi nella periodizzazione lineare semplice.", "La struttura del Giorno A della periodizzazione lineare prevede Squat 3x5, Panca Piana 3x5 e Stacco da Terra 1x5.", "Se le ripetizioni vengono fallite per 3 sessioni consecutive sullo stesso esercizio, è il segnale per eseguire un reset del 10-15% del carico prima di riprendere la progressione."]}
CLAIM ESTRATTI (Modello):
{"claims": ["Il periodo di allenamento dovrebbe essere incrementato di 2,5 kg a sessione su ogni esercizio di spinta e di 5 kg su ogni esercizio di tiro e gambe.", "Le ripetizioni devono essere completeate con la tecnica corretta per aumentare il carico alla sessione successiva secondo i salti programmati.", "Un reset del 10-15% del carico viene effettuato quando il progresso si ferma definitivamente."]}
Calcolo ROUGE e BERTScore in corso...

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

**** METRICHE ****
ROUGE-1: 0.4314
ROUGE-2: 0.2478
ROUGE-L: 0.3391
BERTScore F1: 0.7742

In [24]:
model_lora.save_pretrained("./lora_conf_base")

In [16]:
# Ricarichiamo il modello base
model_checkpoint = "Qwen/Qwen2.5-1.5B-Instruct"

quant_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16, bnb_4bit_quant_type="nf4")

base_model = AutoModelForCausalLM.from_pretrained(model_checkpoint, dtype=torch.float16, quantization_config=quant_config, device_map="auto")

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Adesso aumentiamo il LR a 2e-4

In [18]:
lora_config = LoraConfig(
    r=8, 
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

base_model = prepare_model_for_kbit_training(base_model)

model_lora = get_peft_model(base_model, lora_config)

print(model_lora.print_trainable_parameters())

trainable params: 2,179,072 || all params: 1,545,893,376 || trainable%: 0.1410
None

In [20]:
LR=2e-4

In [21]:
from trl import SFTTrainer, SFTConfig

training_args = SFTConfig(
    output_dir="./finetuning_output",
    learning_rate=LR,
    per_device_train_batch_size=2, 
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=N_EPOCHS,
    report_to="none",
    max_length=MAX_CONTEXT_LENGTH, 
    assistant_only_loss=True,
    optim="adamw_8bit",
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    fp16=False,
    bf16=False,
    eval_strategy="epoch",
    save_strategy="epoch"
)

trainer_lora = SFTTrainer(
    model=model_lora,                    
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
)

/tmp/ipykernel_58/2138342511.py:3: FutureWarning: The default `loss_type` will change from `'nll'` to `'chunked_nll'` in TRL 1.7. For standard models this is transparent (same math, lower memory) and no action is needed — you'll get the new default automatically on upgrade. If you use a custom model, check ahead of time that `loss_type='chunked_nll'` runs and yields the same loss as `'nll'`; if it doesn't, pin `loss_type='nll'` to keep the current behavior and please open an issue at https://github.com/huggingface/trl/issues so we can address the edge case.
  training_args = SFTConfig(

Tokenizing train dataset:   0%|          | 0/261 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/66 [00:00<?, ? examples/s]

In [22]:
trainer_lora.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=99, training_loss=0.6636362123971034, metrics={'train_runtime': 996.7251, 'train_samples_per_second': 0.786, 'train_steps_per_second': 0.099, 'total_flos': 5178291768622080.0, 'train_loss': 0.6636362123971034, 'epoch': 3.0})

In [23]:
evaluate_metrics(model=model_lora, dataset=dataset["validation"])

Generazione claims:   0%|          | 0/66 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

--------------------------------------------------
POST ORIGINALE:
Estrai le 3 affermazioni più importanti e verificabili dal post:

--- POST HOW_TO ---

Titolo: Impostare una Scheda di Forza con Periodizzazione Lineare Semplice per Principianti

La periodizzazione lineare semplice (SLP) è il metodo di programmazione più efficace e validato per principianti e intermedi. Consiste nell'aumentare il carico di allenamento in modo progressivo e sistematico, sessione dopo sessione.

1. PRINCIPIO DI BASE
    1. Sovraccarico progressivo: Ogni sessione di allenamento deve essere leggermente più sfidante della precedente. Per i principianti, aumenti di 2,5 kg a sessione sugli esercizi di spinta (panca, overhead press) e di 5 kg sugli esercizi di tiro e gambe (squat, stacco) sono sostenibili per mesi.
    2. Frequenza: 3 sessioni per settimana (es. lunedì/mercoledì/venerdì), alternando due schemi giornalieri (Giorno A e Giorno B).

2. STRUTTURA DEI GIORNI
    1. Giorno A: Squat 3x5 / Panca Piana 3x5 / Stacco da Terra 1x5
    2. Giorno B: Squat 3x5 / Overhead Press 3x5 / Rematore con Bilanciere 3x5
    3. Gli esercizi principali vengono alternati: La panca si alterna con l'overhead press, entrambe eseguite 1,5 volte a settimana in media.

3. REGOLE PER GLI AUMENTI DI CARICO
    1. Se completi tutte le ripetizioni con la tecnica corretta: aumenta il carico alla sessione successiva secondo i salti programmati.
    2. Se fallisci le ripetizioni per 3 sessioni consecutive sullo stesso esercizio: è il segnale per eseguire un 'reset' del 10-15% del carico e riprendere la progressione.

4. QUANDO PASSARE A UNA PERIODIZZAZIONE PIÙ AVANZATA
    1. Quando la progressione lineare si stalla definitivamente (dopo i reset ripetuti): è il momento di passare a una periodizzazione ondulante o a blocchi.

Fonti:
- Titolo: Starting Strength: Basic Barbell Training (3rd Edition) - Mark Rippetoe, Fonte: [https://www.startingstrength.com/resources/basic-barbell-training](https://www.startingstrength.com/resources/basic-barbell-training)
- Titolo: La periodizzazione lineare per principianti: guida applicata - ForteOggiPiùDiIeri, Fonte: [https://www.forteoggipuidiieri.it/periodizzazione-lineare-principianti](https://www.forteoggipuidiieri.it/periodizzazione-lineare-principianti)...
TARGET CLAIM:
{"claims": ["Per i principianti, aumenti di 2,5 kg a sessione sugli esercizi di spinta e di 5 kg sugli esercizi di tiro e gambe sono sostenibili per mesi nella periodizzazione lineare semplice.", "La struttura del Giorno A della periodizzazione lineare prevede Squat 3x5, Panca Piana 3x5 e Stacco da Terra 1x5.", "Se le ripetizioni vengono fallite per 3 sessioni consecutive sullo stesso esercizio, è il segnale per eseguire un reset del 10-15% del carico prima di riprendere la progressione."]}
CLAIM ESTRATTI (Modello):
{"claims": ["La periodizzazione lineare semplice consiste nell'aumentare il carico di allenamento in modo progressivo e sistematico, aumentando di 2,5 kg a sessione su esercizi di spinta e di 5 kg su esercizi di tiro e gambe.", "Gli esercizi principali vengono alternati tra squat 3x5, pancia piana 3x5 e stacco da terra 1x5, mentre gli esercizi secondari si alternano tra overhead press 3x5 e rematore con bilanciere 3x5.", "Il periodo di reset del 10-15% del carico viene eseguito quando la progressione lineare si stabilizza definitivamente."]}
Calcolo ROUGE e BERTScore in corso...

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

**** METRICHE ****
ROUGE-1: 0.5129
ROUGE-2: 0.3159
ROUGE-L: 0.4247
BERTScore F1: 0.8078

In [24]:
model_lora.save_pretrained("./lora_base_lr2")
tokenizer.save_pretrained("./lora_base_lr2")

('./lora_base_lr2/tokenizer_config.json',
 './lora_base_lr2/chat_template.jinja',
 './lora_base_lr2/tokenizer.json')

In [25]:
import shutil
from IPython.display import FileLink

shutil.make_archive("finetuning_dropout01_lr2", "zip", "/kaggle/working")

FileLink(r"finetuning_dropout01_lr2.zip")

/kaggle/working/finetuning_dropout01_lr2.zip

Adesso aumentiamo il numero di epoche implementando l'early stopping

In [16]:
# Ricarichiamo il modello base
model_checkpoint = "Qwen/Qwen2.5-1.5B-Instruct"

quant_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16, bnb_4bit_quant_type="nf4")

base_model = AutoModelForCausalLM.from_pretrained(model_checkpoint, dtype=torch.float16, quantization_config=quant_config, device_map="auto")

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [18]:
N_EPOCHS = 5
LR = 2e-4

In [20]:
lora_config = LoraConfig(
    r=8, 
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

base_model = prepare_model_for_kbit_training(base_model)

model_lora = get_peft_model(base_model, lora_config)

print(model_lora.print_trainable_parameters())

trainable params: 2,179,072 || all params: 1,545,893,376 || trainable%: 0.1410
None

In [21]:
from trl import SFTTrainer, SFTConfig

training_args = SFTConfig(
    output_dir="./finetuning_output",
    learning_rate=LR,
    per_device_train_batch_size=2, 
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=N_EPOCHS,
    report_to="none",
    max_length=MAX_CONTEXT_LENGTH, 
    assistant_only_loss=True,
    optim="adamw_8bit",
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    fp16=False,
    bf16=False,
    
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,     
    metric_for_best_model="eval_loss",
    greater_is_better=False,         
)

trainer_lora = SFTTrainer(
    model=model_lora,                    
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
)

/tmp/ipykernel_58/1077446501.py:3: FutureWarning: The default `loss_type` will change from `'nll'` to `'chunked_nll'` in TRL 1.7. For standard models this is transparent (same math, lower memory) and no action is needed — you'll get the new default automatically on upgrade. If you use a custom model, check ahead of time that `loss_type='chunked_nll'` runs and yields the same loss as `'nll'`; if it doesn't, pin `loss_type='nll'` to keep the current behavior and please open an issue at https://github.com/huggingface/trl/issues so we can address the edge case.
  training_args = SFTConfig(

Tokenizing train dataset:   0%|          | 0/261 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/66 [00:00<?, ? examples/s]

In [22]:
trainer_lora.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=165, training_loss=0.5971359686418013, metrics={'train_runtime': 1658.2383, 'train_samples_per_second': 0.787, 'train_steps_per_second': 0.1, 'total_flos': 8624986823577600.0, 'train_loss': 0.5971359686418013, 'epoch': 5.0})

Sopra vediamo che a partire dall'epoca 4 la validation loss aumenta, questo è un segnale di overfitting.

Adesso consideriamo la configurazione in cui aumentiamo la capacità di LoRA portando il rango da 8 a 16

In [14]:
# Ricarichiamo il modello base
model_checkpoint = "Qwen/Qwen2.5-1.5B-Instruct"

quant_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16, bnb_4bit_quant_type="nf4")

base_model = AutoModelForCausalLM.from_pretrained(model_checkpoint, dtype=torch.float16, quantization_config=quant_config, device_map="auto")

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [15]:
# Aumentiamo il rango di LoRA da 8 a 16
lora_config = LoraConfig(
    r=16, 
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.CAUSAL_LM
)

base_model = prepare_model_for_kbit_training(base_model)

model_lora = get_peft_model(base_model, lora_config)

print(model_lora.print_trainable_parameters())

trainable params: 4,358,144 || all params: 1,548,072,448 || trainable%: 0.2815
None

In [16]:
N_EPOCHS = 3
LR = 2e-4

In [17]:
from trl import SFTTrainer, SFTConfig

training_args = SFTConfig(
    output_dir="./finetuning_output",
    learning_rate=LR,
    per_device_train_batch_size=2, 
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=N_EPOCHS,
    report_to="none",
    max_length=MAX_CONTEXT_LENGTH, 
    assistant_only_loss=True,
    optim="adamw_8bit",
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    fp16=False,
    bf16=False,
    eval_strategy="epoch",
    save_strategy="epoch"
)

trainer_lora = SFTTrainer(
    model=model_lora,                    
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
)

/tmp/ipykernel_58/2138342511.py:3: FutureWarning: The default `loss_type` will change from `'nll'` to `'chunked_nll'` in TRL 1.7. For standard models this is transparent (same math, lower memory) and no action is needed — you'll get the new default automatically on upgrade. If you use a custom model, check ahead of time that `loss_type='chunked_nll'` runs and yields the same loss as `'nll'`; if it doesn't, pin `loss_type='nll'` to keep the current behavior and please open an issue at https://github.com/huggingface/trl/issues so we can address the edge case.
  training_args = SFTConfig(

Tokenizing train dataset:   0%|          | 0/261 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/66 [00:00<?, ? examples/s]

In [18]:
trainer_lora.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=99, training_loss=0.6338240209251943, metrics={'train_runtime': 986.9304, 'train_samples_per_second': 0.793, 'train_steps_per_second': 0.1, 'total_flos': 5186888874458112.0, 'train_loss': 0.6338240209251943, 'epoch': 3.0})

In [21]:
evaluate_metrics(model=model_lora, dataset=dataset["validation"])

Generazione claims:   0%|          | 0/66 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

--------------------------------------------------
POST ORIGINALE:
Estrai le 3 affermazioni più importanti e verificabili dal post:

--- POST HOW_TO ---

Titolo: Impostare una Scheda di Forza con Periodizzazione Lineare Semplice per Principianti

La periodizzazione lineare semplice (SLP) è il metodo di programmazione più efficace e validato per principianti e intermedi. Consiste nell'aumentare il carico di allenamento in modo progressivo e sistematico, sessione dopo sessione.

1. PRINCIPIO DI BASE
    1. Sovraccarico progressivo: Ogni sessione di allenamento deve essere leggermente più sfidante della precedente. Per i principianti, aumenti di 2,5 kg a sessione sugli esercizi di spinta (panca, overhead press) e di 5 kg sugli esercizi di tiro e gambe (squat, stacco) sono sostenibili per mesi.
    2. Frequenza: 3 sessioni per settimana (es. lunedì/mercoledì/venerdì), alternando due schemi giornalieri (Giorno A e Giorno B).

2. STRUTTURA DEI GIORNI
    1. Giorno A: Squat 3x5 / Panca Piana 3x5 / Stacco da Terra 1x5
    2. Giorno B: Squat 3x5 / Overhead Press 3x5 / Rematore con Bilanciere 3x5
    3. Gli esercizi principali vengono alternati: La panca si alterna con l'overhead press, entrambe eseguite 1,5 volte a settimana in media.

3. REGOLE PER GLI AUMENTI DI CARICO
    1. Se completi tutte le ripetizioni con la tecnica corretta: aumenta il carico alla sessione successiva secondo i salti programmati.
    2. Se fallisci le ripetizioni per 3 sessioni consecutive sullo stesso esercizio: è il segnale per eseguire un 'reset' del 10-15% del carico e riprendere la progressione.

4. QUANDO PASSARE A UNA PERIODIZZAZIONE PIÙ AVANZATA
    1. Quando la progressione lineare si stalla definitivamente (dopo i reset ripetuti): è il momento di passare a una periodizzazione ondulante o a blocchi.

Fonti:
- Titolo: Starting Strength: Basic Barbell Training (3rd Edition) - Mark Rippetoe, Fonte: [https://www.startingstrength.com/resources/basic-barbell-training](https://www.startingstrength.com/resources/basic-barbell-training)
- Titolo: La periodizzazione lineare per principianti: guida applicata - ForteOggiPiùDiIeri, Fonte: [https://www.forteoggipuidiieri.it/periodizzazione-lineare-principianti](https://www.forteoggipuidiieri.it/periodizzazione-lineare-principianti)...
TARGET CLAIM:
{"claims": ["Per i principianti, aumenti di 2,5 kg a sessione sugli esercizi di spinta e di 5 kg sugli esercizi di tiro e gambe sono sostenibili per mesi nella periodizzazione lineare semplice.", "La struttura del Giorno A della periodizzazione lineare prevede Squat 3x5, Panca Piana 3x5 e Stacco da Terra 1x5.", "Se le ripetizioni vengono fallite per 3 sessioni consecutive sullo stesso esercizio, è il segnale per eseguire un reset del 10-15% del carico prima di riprendere la progressione."]}
CLAIM ESTRATTI (Modello):
{"claims": ["Nel periodo di base, ogni sessione di allenamento deve essere leggermente più sfidante rispetto alla precedente.", "Il programma consiste in 3 sessioni per settimana, alternando due schemi giornalieri (Giorno A e Giorno B).", "Se falliscono le ripetizioni per 3 sessioni consecutive su uno specifico esercizio, è necessario eseguirne un reset del 10-15% del carico."]}
Calcolo ROUGE e BERTScore in corso...

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

**** METRICHE ****
ROUGE-1: 0.5220
ROUGE-2: 0.3199
ROUGE-L: 0.4263
BERTScore F1: 0.8135

In [20]:
full_finetuned_model = model_lora.merge_and_unload()
full_finetuned_model.save_pretrained("./finetuned_model")
tokenizer.save_pretrained("./finetuned_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./finetuned_model/tokenizer_config.json',
 './finetuned_model/chat_template.jinja',
 './finetuned_model/tokenizer.json')

In [21]:
import shutil
from IPython.display import FileLink

shutil.make_archive("finetuned_model", "zip", "/kaggle/working")

FileLink(r"finetuned_model.zip")

/kaggle/working/finetuned_model.zip

Quest'ultima configurazione è la migliore sia in termini di loss che in termini delle metriche ROUGE e BERTScore. Procediamo con la valutazione sul test set

In [24]:
evaluate_metrics(model=model_lora, dataset=dataset["test"])

Generazione claims:   0%|          | 0/82 [00:00<?, ?it/s]

--------------------------------------------------
POST ORIGINALE:
Estrai le 3 affermazioni più importanti e verificabili dal post:

--- POST NEWS ---

Titolo: Studio Pubblicato su Amino Acids Dimostra l'Efficacia della Citrullina Malato sulla Riduzione della Fatica Muscolare Acuta

Una ricerca scientifica in doppio cieco ha analizzato gli effetti dell'integrazione acuta di L-citrullina legata all'acido malico sulla clearance dell'ammoniaca e sulla risintesi del fosfocreatina durante protocolli di forza.

SCOPERTE CHIAVE DELLO STUDIO CLINICO
    1 Tampone dell'Ammoniaca via Ciclo dell'Urea: La L-citrullina stimola la clearance plasmatica dell'ammoniaca e del lattato prodotti durante la glicolisi anaerobica, ritardando l'insorgenza della fatica muscolare periferica.
    2 Incremento dell'ATP e della Risintesi di CP: Il legame con il malato (un intermedio del ciclo di Krebs) stimola la produzione di ATP ossidativo durante il riposo tra le serie, incrementando del 34% il tasso di risintesi della fosfocreatina.
    3 Aumento delle Ripetizioni a Cedimento: Il gruppo che ha assunto citrullina malato ha eseguito il 19% in più di ripetizioni nell'ultima serie di panca piana rispetto al gruppo placebo.

PROTOCOLLO DI INTEGRAZIONE EFFICACE
    1 Assumere una dose di 8 grammi di Citrullina Malato (in rapporto 2:1) circa 60 minutes prima dell'allenamento, preferibilmente a stomaco vuoto per massimizzare la cinetica di assorbimento.

CONCLUSIONE
La citrullina malato non è un semplice precursore dell'ossido nitrico per il pump, ma un potente modulatore metabolico in grado di innalzare la capacità di lavoro totale della sessione.

Fonti:
- Titolo: Citrulline malate enhances athletic performance and adenosine triphosphate production during intensive exercise • Journal of Amino Acids Research, Fonte: https://www.jaar.org/citrulline-malate-atp-synthesis
- Titolo: Metabolismo energetico della citrullina malato nello sport della forza - Nutrizione Scientifica, Fonte: https://www.nutrizionescientifica.it/citrullina-malato-fatica...
TARGET CLAIM:
{"claims": ["La combinazione con l'acido malico stimola l'ATP ossidativo a riposo, determinando un incremento del 34% nel tasso di risintesi della fosfocreatina.", "Gli atleti che hanno integrato con citrullina malato hanno completato il 19% di ripetizioni in più nell'ultima serie di panca piana.", "Il protocollo suggerito richiede l'assunzione di 8 grammi di Citrullina Malato (in rapporto 2:1) circa 60 minuti prima dell'attività."]}
CLAIM ESTRATTI (Modello):
{"claims": ["L-citrullina stimola la clearance plasmatica dell'ammoniaca e del lattato prodotti durante la glicolisi anaerobica.", "Il legame con il malato incrementa del 34% il tasso di risintesi della fosfocreatina.", "Un protocollo efficace prevede l'assunzione di 8 grammi di citrullina malato in rapporto 2:1 60 minuti prima dell'allenamento."]}
Calcolo ROUGE e BERTScore in corso...

**** METRICHE ****
ROUGE-1: 0.4757
ROUGE-2: 0.2719
ROUGE-L: 0.3673
BERTScore F1: 0.7921

In [25]:
# Ricarichiamo il modello base
model_checkpoint = "Qwen/Qwen2.5-1.5B-Instruct"

quant_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16, bnb_4bit_quant_type="nf4")

base_model = AutoModelForCausalLM.from_pretrained(model_checkpoint, dtype=torch.float16, quantization_config=quant_config, device_map="auto")

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [27]:
evaluate_metrics(model=base_model, dataset=dataset["test"])

Generazione claims:   0%|          | 0/82 [00:00<?, ?it/s]

--------------------------------------------------
POST ORIGINALE:
Estrai le 3 affermazioni più importanti e verificabili dal post:

--- POST NEWS ---

Titolo: Studio Pubblicato su Amino Acids Dimostra l'Efficacia della Citrullina Malato sulla Riduzione della Fatica Muscolare Acuta

Una ricerca scientifica in doppio cieco ha analizzato gli effetti dell'integrazione acuta di L-citrullina legata all'acido malico sulla clearance dell'ammoniaca e sulla risintesi del fosfocreatina durante protocolli di forza.

SCOPERTE CHIAVE DELLO STUDIO CLINICO
    1 Tampone dell'Ammoniaca via Ciclo dell'Urea: La L-citrullina stimola la clearance plasmatica dell'ammoniaca e del lattato prodotti durante la glicolisi anaerobica, ritardando l'insorgenza della fatica muscolare periferica.
    2 Incremento dell'ATP e della Risintesi di CP: Il legame con il malato (un intermedio del ciclo di Krebs) stimola la produzione di ATP ossidativo durante il riposo tra le serie, incrementando del 34% il tasso di risintesi della fosfocreatina.
    3 Aumento delle Ripetizioni a Cedimento: Il gruppo che ha assunto citrullina malato ha eseguito il 19% in più di ripetizioni nell'ultima serie di panca piana rispetto al gruppo placebo.

PROTOCOLLO DI INTEGRAZIONE EFFICACE
    1 Assumere una dose di 8 grammi di Citrullina Malato (in rapporto 2:1) circa 60 minutes prima dell'allenamento, preferibilmente a stomaco vuoto per massimizzare la cinetica di assorbimento.

CONCLUSIONE
La citrullina malato non è un semplice precursore dell'ossido nitrico per il pump, ma un potente modulatore metabolico in grado di innalzare la capacità di lavoro totale della sessione.

Fonti:
- Titolo: Citrulline malate enhances athletic performance and adenosine triphosphate production during intensive exercise • Journal of Amino Acids Research, Fonte: https://www.jaar.org/citrulline-malate-atp-synthesis
- Titolo: Metabolismo energetico della citrullina malato nello sport della forza - Nutrizione Scientifica, Fonte: https://www.nutrizionescientifica.it/citrullina-malato-fatica...
TARGET CLAIM:
{"claims": ["La combinazione con l'acido malico stimola l'ATP ossidativo a riposo, determinando un incremento del 34% nel tasso di risintesi della fosfocreatina.", "Gli atleti che hanno integrato con citrullina malato hanno completato il 19% di ripetizioni in più nell'ultima serie di panca piana.", "Il protocollo suggerito richiede l'assunzione di 8 grammi di Citrullina Malato (in rapporto 2:1) circa 60 minuti prima dell'attività."]}
CLAIM ESTRATTI (Modello):
{"claims": ["L-citrullina stimulates the clearance of ammonia and lactate produced during anaerobic glycolysis, delaying peripheral fatigue", "The citrulline malate supplement increases ATP production and phosphocreatine synthesis during rest between sets", "Citrulline malate improves endurance by increasing the number of repetitions performed"]}
Calcolo ROUGE e BERTScore in corso...

**** METRICHE ****
ROUGE-1: 0.1985
ROUGE-2: 0.0853
ROUGE-L: 0.1535
BERTScore F1: 0.6846

Adesso proviamo ad estrarre i claims da un post reale generato dal nostro agente usando sia il nostro modello finetunato che la baseline

In [28]:
def generate_claims(model, tokenizer, post):
    model.eval()
    original_padding_side = tokenizer.padding_side
    tokenizer.padding_side = "left"
    
    with torch.no_grad():
        prompt_str = tokenizer.apply_chat_template([
            {"role": "system", "content": "Sei un sistema di estrazione dati che lavora ESCLUSIVAMENTE sul testo fornito dall'utente. Il tuo compito è analizzare il testo e estrarre le informazioni presenti. Rispondi ESCLUSIVAMENTE in lingua italiana. Se un'informazione non è nel testo, non includerla. Rispondi SOLO in formato JSON: {'claims': ['claim1', 'claim2', 'claim3']} senza aggiungere altre informazioni."},
            {"role": "user", "content": f"Estrai le 3 affermazioni più importanti e verificabili dal post:\n\n{post}"}
        ], tokenize=False, add_generation_prompt=True)
        
        inputs = tokenizer(prompt_str, return_tensors="pt").to(model.device)

        outputs = model.generate(
            **inputs,
            max_new_tokens=512, 
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id
        )
        
        input_length = inputs.input_ids.shape[1]
        generated_tokens = outputs[0][input_length:]
        pred_text = tokenizer.decode(generated_tokens, skip_special_tokens=True)
        
        print(f"CLAIM ESTRATTI:\n{pred_text}")
        
        tokenizer.padding_side = original_padding_side

In [29]:
post = """Titolo: Recensione Nike Metcon 7: La scarpa definitiva per squat e allenamento funzionale?


Categoria: REVIEW


Le Nike Metcon 7 si presentano come un punto di riferimento per chi cerca stabilità e versatilità nell'allenamento, in particolare per squat, sollevamento pesi e sessioni di CrossFit. Analizziamo le caratteristiche che le rendono una scelta popolare tra gli atleti.
CARATTERISTICHE PRINCIPALI


Stabilità per il sollevamento pesi: Suola piatta e ampia con piastra interna nel tallone per una base stabile in squat e stacchi.
Ammortizzazione React Foam: Schiuma Nike React nell'avampiede per comfort in cardio e HIIT, mantenendo stabilità.
Sistema di allacciatura e vestibilità: Chiusura a strappo per calzata sicura. Calzata stretta, considerare mezzo numero in più.
Dettagli funzionali: Rope Guard per aderenza in salita corda e clip sul tallone per verticali. Drop tacco-punta di 4 mm.

PRO


Eccellente stabilità per squat e sollevamento pesi.
Buona ammortizzazione per brevi sessioni cardio e HIIT.
Design accattivante e ampia scelta di colorazioni.
Costruzione robusta e durevole.

CONTRO


Prezzo elevato (circa $130).
Non ideali per la corsa su lunghe distanze.
La calzata può risultare stretta per alcuni.

Le Nike Metcon 7 si confermano una scelta eccellente per gli atleti che praticano sollevamento pesi, CrossFit e allenamento funzionale, offrendo un equilibrio notevole tra stabilità e comfort. Sebbene il prezzo sia un fattore da considerare e non siano le scarpe ideali per la corsa prolungata, la loro versatilità e le caratteristiche specifiche per l'allenamento le rendono un investimento valido per migliorare le prestazioni in palestra.


Fonti: ['https://www.garagegymreviews.com/nike-metcon-7-review', 'https://fitatmidlife.com/nike-metcon-7-crossfit-shoe-review', 'https://www.menshealth.com/uk/gym-wear/a37178090/nike-metcon-7-review']
"""

In [30]:
generate_claims(model_lora, tokenizer, post)

CLAIM ESTRATTI:
{"claims": ["Le Nike Metcon 7 sono dotate di schiuma Nike React nell'avampiede per ammortizzare i movimenti e mantenere la stabilità durante sessioni di cardio e HIIT.", "Il design della Nike Metcon 7 offre una chiusura a strappo per garantire una calzata sicura e una calzata stretta richiede il mezzo numero in più.", "L'analisi del post conclude che le Nike Metcon 7 sono un buon investimento per atleti che pratichiscono sollevamento pesi, CrossFit e allenamento funzionale."]}

In [33]:
generate_claims(base_model, tokenizer, post)

CLAIM ESTRATTI:
{"claims": ["Nike Metcon 7 is a point of reference for those who seek stability and versatility in training, especially for squats and weightlifting", "The Nike Metcon 7 offers excellent stability for squatting and lifting weights", "The Nike Metcon 7 provides good shock absorption for short cardio sessions and HIIT"]}